version: '3.8'
services:
  fetcher:
    build: ./fetcher
    container_name: pipeline-fetcher
    volumes:
      - pipeline-data:/shared
    environment:
      - PYTHONUNBUFFERED=1
  processor:
    build: ./processor
    container_name: pipeline-processor
    volumes:
      - pipeline-data:/shared
    depends_on:
      - fetcher
    environment:
      - PYTHONUNBUFFERED=1
  analyzer:
    build: ./analyzer
    container_name: pipeline-analyzer
    volumes:
      - pipeline-data:/shared
    depends_on:
      - processor
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  pipeline-data:
    name: pipeline-shared-data
